export const cointegrationPairsTradingDiscussionQuestions = [
  {
    id: 1,
    question:
      "Design a production pairs trading system for a hedge fund with $500M AUM trading 50 pairs simultaneously. Address: (1) Pair selection methodology (screening universe of 500 stocks), (2) How to handle time-varying hedge ratios vs static ratios, (3) Risk management when multiple pairs become correlated during market stress, (4) Operational issues: execution, slippage, financing costs for short positions, (5) Performance attribution: which pairs contribute to alpha vs drag, and (6) When to retire underperforming pairs without overfitting to recent data.",
    answer: `[Comprehensive outline: Pair selection using rolling cointegration tests + minimum trading volume/liquidity filters + sector neutrality; Dynamic hedge ratios via rolling regression (60-day window) vs Kalman filter for real-time updating; Correlation stress testing showing pairs can synchronize during crises → portfolio-level VaR limits + diversification across sectors; Execution using VWAP algorithms, modeling 5-10bps slippage, borrow costs 20-50bps/year for shorts; Attribution via spread P&L decomposition; Retirement criteria: 6-month rolling Sharpe < 0.5 + cointegration p-value > 0.10 for 3 consecutive months. Full implementation would include code for each component with backtesting framework.]`,
  },
  {
    id: 2,
    question:
      "A pairs trader finds SPY (S&P 500 ETF) and IVV (another S&P 500 ETF) are 'perfectly' cointegrated with Engle-Granger p-value < 0.001. The strategy shows 15% annual returns in backtest. However, a senior trader says: 'This is not true statistical arbitrage - you're just trading noise around near-perfect substitutes with transaction costs eating your alpha.' Explain: (1) Why ETFs tracking the same index are trivially cointegrated, (2) The difference between statistical cointegration and economic cointegration (fundamental reasons for mean reversion), (3) Why this strategy likely won't work in practice (bid-ask spreads, tracking differences), (4) Examples of economically cointegrated pairs that do work (e.g., integrated oil companies, spot-futures relationships), and (5) How to evaluate whether a cointegrated relationship has economic substance vs is purely statistical.",
    answer: `[Comprehensive outline: ETFs tracking same index are nearly identical → trivial cointegration with no alpha opportunity; Economic cointegration requires fundamental linkage (supply chain, arbitrage mechanism, substitutes with switching costs); Bid-ask spreads on ETFs ~1bp, but profitable spread opportunities <0.5bp → negative expected return after costs; Good examples: XOM-CVX (both integrated oils with similar business models), spot gold-gold futures (storage cost arbitrage), KO-PEP (substitute products with brand loyalty creating mean reversion); Evaluation framework: Test economic hypothesis, check if spread predicts fundamentals, analyze cost-of-carry or arbitrage mechanisms, verify profitability net of all costs. Include code demonstrating the calculation.]`,
  },
  {
    id: 3,
    question:
      "Compare three approaches to pairs trading: (A) Engle-Granger with static hedge ratio, (B) Rolling regression with time-varying hedge ratios updated daily, (C) Kalman filter for dynamic hedge ratio and spread estimation. For a trading system targeting daily rebalancing with 1-week holding periods: Which approach is theoretically superior? Which performs best empirically? What are the computational trade-offs? Design an experiment to test all three on historical equity data and explain why results might differ from theory.",
    answer: `[Comprehensive outline: Theory: Kalman filter optimal for time-varying parameters; Engle-Granger assumes constant relationship (restrictive); Rolling regression intermediate; Empirics: Kalman often overfits to noise, rolling regression (30-60 day window) performs best in practice, static hedge ratio surprisingly competitive due to overfitting prevention; Computational: Kalman O(1) per update, rolling O(n) per window, static O(1); Experiment design: 10-year backtest, 100 pairs, compare Sharpe ratios and turnover; Results differ because: real cointegration relationships are slow-moving, daily hedge ratio changes mostly noise, transaction costs penalize excessive rebalancing. Code implementation demonstrating each approach with performance comparison.]`,
  },
];

