export const riskAssessmentLLMsQuiz = {
  title: 'Risk Assessment with LLMs Discussion',
  id: 'risk-assessment-llms-quiz',
  sectionId: 'risk-assessment-llms',
  questions: [
    {
      id: 1,
      question:
        'How can LLMs help identify "soft" credit risks that traditional quantitative models miss? Discuss examples of qualitative red flags that might appear in management discussion, tone, or narrative changes that predict financial distress before it appears in the numbers.',
      expectedAnswer: `Should discuss: traditional credit models use financial ratios and historical data, missing early warning signs in qualitative information. LLM advantages: detect management tone shifts from confident to defensive across filings over time, identify vague or evasive language around liquidity or operations, notice increased use of hedging language and caveats, track CEO/CFO turnover mentions and explanations, spot conflicts between narrative and numbers (saying "strong" while metrics declining), identify subtle changes in business description suggesting strategic confusion, and recognize increasingly aggressive accounting explanations. Examples: "challenging environment" appearing more frequently, transitioning from specific metrics to general statements, risk factors section expanding significantly, management discussion and analysis becoming wordier without adding information, and comparing management tone to peer companies in same conditions. Qualitative leads quantitative: management knows problems before they fully appear in results, linguistic analysis can detect stress, and changes in communication patterns often precede deterioration. Limitation: false positives from management style changes, industry jargon differences, and LLM misreading context. Best use: screening tool that elevates companies for deeper analysis rather than automatic decisions.`,
    },
    {
      id: 2,
      question:
        'What are the challenges of using LLMs for geopolitical risk assessment, particularly around predicting impact timing and magnitude? How should systems balance being proactive vs reactive to geopolitical events?',
      expectedAnswer: `Should cover: geopolitical events are inherently unpredictable-LLMs can assess impact once events occur but not predict black swans reliably. Challenges: same event (e.g., sanctions) can have vastly different impacts depending on execution details unknown until they happen, second and third-order effects often larger than direct impacts, market reactions often irrational short-term before settling to fair value, and attribution problems where multiple factors coincide. Timing uncertainty: sanctions announced today may impact business in 6-18 months, or never if workarounds found. Magnitude uncertainty: supply chain disruptions can range from inconvenient to business-ending depending on specifics. LLM value: rapidly assess exposure once event occurs, identify which portfolio companies affected and how, synthesize diverse information sources, and learn from historical similar events. Proactive vs reactive: maintain "risk library" of potential events and exposures but don't overreact to possibilities (everything is possible), monitor news for early warnings but recognize difference between speculation and reality, pre-position defensively only for high-probability, high-impact events, use most resources reacting quickly to actual events rather than predicting hypothetical ones. Balance: scenario analysis for known risks (elections, policy changes), real-time response system for surprises, and acknowledgment that some risks are inherently unpredictable so portfolios need general resilience not specific predictions.`,
    },
    {
      id: 3,
      question:
        'How should early warning systems for financial risk balance sensitivity (catching real problems early) with specificity (avoiding false alarms)? Discuss the costs of both false negatives and false positives and optimal threshold setting strategies.',
      expectedAnswer: `Should analyze: perfect sensitivity means many false alarms (crying wolf), perfect specificity means missing real problems. Costs differ: false negative (missing real risk) can mean large losses or total loss if company fails; false positive (false alarm) means wasted investigation time, alert fatigue causing real alerts to be ignored, and potential opportunity cost if good company is avoided due to false flag. Optimal threshold depends on: portfolio concentration (concentrated position warrants lower threshold), company criticality (key holdings or counterparties need tighter monitoring), and investigation capacity (if team can investigate 10 alerts/day, can afford lower threshold than if only 2/day). Strategy: tiered alert system with high/medium/low severity, use confidence scores not binary flags, track historical false positive rates to calibrate thresholds, different thresholds for different risk types (lower for liquidity risk than for long-term solvency), implement "confirmation required" for borderline signals before escalating, and automatic escalation paths (low alerts go to analyst, high alerts go to risk officer). Continuous improvement: measure both false positive rate and false negative rate, adjust thresholds based on alert resolution outcomes, track time from alert to problem materialization to optimize lead time, and consider asymmetric costs-in risk management, false negatives typically more costly than false positives so bias toward sensitivity within reason. Ultimate: acknowledge no perfect threshold exists, build investigation processes that can handle volume of alerts generated at chosen threshold.`,
    },
  ],
};
