export const tradingSignalGenerationQuiz = {
  title: 'Trading Signal Generation Discussion',
  id: 'trading-signal-generation-quiz',
  sectionId: 'trading-signal-generation',
  questions: [
    {
      id: 1,
      question:
        'When integrating multiple signal sources (technical, fundamental, sentiment, quantitative models) using LLMs, how should conflicting signals be handled? Discuss the framework for resolving disagreements and the risks of either simple averaging or complex meta-modeling.',
      expectedAnswer: `Should discuss: conflicts reveal uncertainty and should not be hidden by averaging-a technical buy + fundamental sell is different information than two neutral signals. Simple averaging loses information about disagreement and can mask strong single-factor signals. Complex meta-modeling risks overfitting to historical conflict resolution patterns that may not generalize. Framework: explicitly identify and characterize conflicts, understand why sources disagree (different time horizons, information sets, or market views), weight by historical accuracy in current market regime, consider signal strength not just direction, and present uncertainty explicitly rather than false confidence. LLM advantage: can reason about conflict causes-technical breakout vs fundamental deterioration may favor one depending on market environment. Risks: LLM may rationalize contradictions that should trigger caution, can anthropomorphize analysis (treating signals as "opinions" to reconcile rather than data), and may be overly confident in synthesis. Best practice: use LLM to explain conflicts and suggest resolution framework, but maintain quantitative weighting system for actual trading decisions, escalate high-conflict situations to human review, and track when conflicts predicted poor performance.`,
    },
    {
      id: 2,
      question:
        'How should confidence scores on trading signals be calibrated and validated? What makes a confidence score meaningful vs misleading, and how can historical performance be used to improve calibration?',
      expectedAnswer: `Should cover: confidence scores must be calibrated-if system says 80% confidence for 100 trades, roughly 80 should be profitable for scores to be meaningful. Uncalibrated confidence is worse than no confidence as it creates false certainty. LLMs tend toward overconfidence (rarely output extreme low/high confidence even when appropriate). Calibration process: backtest signals with recorded confidence, measure actual win rate by confidence bucket, adjust scoring to match reality. Validation: out-of-sample testing, different market regimes, different securities. Meaningful confidence factors: agreement across signals, statistical significance of patterns, quality of data inputs, historical accuracy in similar situations. Misleading: based on model's internal uncertainty which may not correlate with actual accuracy, confusing precision with confidence, not accounting for regime changes. Use confidence for: position sizing (higher confidence = larger position within risk limits), decision thresholds (only trade high-confidence signals), and resource allocation (high-value low-confidence signals get human review). Track and report: calibration metrics to ensure scores remain meaningful, recalibrate regularly as markets evolve, and be honest about uncertainty-clear statement "low confidence but positive expected value" more useful than false certainty.`,
    },
    {
      id: 3,
      question:
        'What are the second-order effects and potential systemic risks when many market participants use similar LLM-powered signal generation systems? How might this create new market dynamics and what strategies can mitigate crowding risk?',
      expectedAnswer: `Should analyze: if everyone uses similar LLMs reading same news to generate same signals, trades become crowded and alpha degrades. Self-fulfilling prophecies: LLM-driven buying creates the price move that confirms the signal, but reverses when no more buyers. Flash crashes: when LLMs all trigger sells simultaneously on same news interpretation. Signal degradation: profitable patterns disappear as they become widely exploited. Regime instability: market correlation increases as diverse strategies consolidate to similar LLM-driven approaches. Systemic risks: feedback loops where LLM signals cause market moves that generate more LLM signals, reduced diversity in market making, and concentration of trading logic in few foundation models. Mitigation strategies: use proprietary data sources inaccessible to others, implement contrarian signals specifically for crowded trades, maintain diverse strategy portfolio including non-LLM approaches, monitor market microstructure for signs of crowding (correlated order flow), and deliberately add randomization or delay to avoid perfect synchronization with other LLM systems. Consider: advantage may shift from best analysis to unique analysis, speed arms race creates winner-take-all dynamics favoring infrastructure over insight, and regulatory response may limit certain types of algorithmic trading. Strategy: focus on longer time horizons where LLM crowding less severe, find orthogonal signals others miss, or accept lower returns in exchange for lower crowding risk.`,
    },
  ],
};
